# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-13 03:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='date_joined',
        ),
    ]
