# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-19 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0002_remove_userprofileinfo_date_joined'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitProfileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_first_name', models.CharField(max_length=40)),
                ('player_last_name', models.CharField(max_length=40)),
                ('player_position', models.CharField(max_length=5)),
                ('player_height', models.CharField(max_length=5)),
                ('player_weight', models.IntegerField()),
                ('player_school', models.CharField(max_length=40)),
                ('player_state', models.CharField(max_length=2)),
                ('player_phone', models.CharField(blank=True, max_length=15)),
                ('player_twitter', models.CharField(blank=True, max_length=40)),
            ],
        ),
    ]
