# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-19 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0003_recruitprofileinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='NationalRecruitList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_grad_year', models.IntegerField()),
                ('player_rivals_rank', models.IntegerField()),
                ('player_espn_rank', models.IntegerField()),
                ('player_first_name', models.CharField(max_length=40)),
                ('player_last_name', models.CharField(max_length=40)),
                ('player_position', models.CharField(max_length=5)),
                ('player_school', models.CharField(max_length=40)),
                ('player_state', models.CharField(max_length=2)),
                ('player_height', models.CharField(max_length=5)),
                ('player_weight', models.IntegerField()),
                ('player_potential_schools', models.CharField(max_length=260)),
            ],
        ),
        migrations.AddField(
            model_name='recruitprofileinfo',
            name='player_grad_year',
            field=models.IntegerField(default=2016),
            preserve_default=False,
        ),
    ]
