# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-19 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0004_auto_20170719_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nationalrecruitlist',
            name='player_potential_schools',
            field=models.CharField(blank=True, max_length=260),
        ),
    ]
